# Site Information
site_name: Sanji
site_url: https://prateekrai-atlan.github.io/sanji/
site_author: Prateek Rai
site_description: Sanji is a personal website for Prateek Rai. It is a collection of blogs, personal opinions, and rants.
copyright: >-
  Copyright &copy; 2025 Prateek Rai

# Repository Information
repo_name: sanji
repo_url: https://github.com/prateek11rai/sanji

# Theme Configuration (Material)
theme:
  name: material
  language: en
  custom_dir: overrides
  font:
    text: Google Sans Code
    code: Google Sans Code
  favicon: logos/strawhat.png
  icon:
    logo: logos/strawhat
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: gray
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: gray
      toggle:
        icon: material/weather-night
        name: Switch to system preference

# Documentation Configuration
docs_dir: docs

# Nav Configuration
nav:
  - Me: index.md
  - Projects: 
      - Projects: projects/index.md
      - Doc Aid: 
        - Doc Aid: projects/doc-aid/index.md
  - Blog:
    - blog/index.md

# Attributes addition
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Extra Configuration
extra:
  # generator: false (https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice)
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/prateek11rai/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/prateek11rai
      name: GitHub
    - icon: fontawesome/brands/goodreads-g
      link: https://www.goodreads.com/user/show/186922946-prateek-rai
      name: GoodReads
    - icon: fontawesome/brands/strava
      link: https://www.strava.com/athletes/prateek11rai
      name: Strava
    - icon: logos/myanimelist
      link: https://myanimelist.net/animelist/prateek11rai
      name: MyAnimeList
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@prateek11rai
      name: YouTube
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/prateek11rai
      name: Instagram
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/prateek11rai
      name: X
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/prateek11rai
      name: Facebook

# Plugins
plugins:
  - meta:
      enabled: true
  - search:
      enabled: true
  - social:
      enabled: true
  - blog:
      authors: true
      draft_on_serve: true
      draft: true
      authors_profile: true